# syntax=docker/dockerfile:1

FROM golang:1.24.3

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy all source code
COPY . .

# Run integration tests
CMD ["go", "test", "-v", "./integration/..."]